UPDATE mangos_string SET content_default = "The %s field of %s was set to %u" WHERE entry= '299';

REPLACE INTO `command` (`name`, `security`, `help`) VALUES('honor add','2','Syntax: .honor add $amount\r\n\r\nAdd a certain amount of honor (gained in lifetime) to the selected player.');
REPLACE INTO `command` (`name`, `security`, `help`) VALUES('honor addkill','2','Syntax: .honor addkikll\r\n\r\nAdd the targeted unit as one of your pvp kills today (you only get honor if it\'s a racial leader or a player)');
REPLACE INTO `command` (`name`, `security`, `help`) VALUES('honor update','2','Syntax: .honor update\r\n\r\nForce honor to be update');
REPLACE INTO `command` (`name`, `security`, `help`) VALUES('honor show','1','Syntax: .honor show\r\n\r\nDisplay the honor stats of the selected player');
REPLACE INTO `command` (`name`, `security`, `help`) VALUES('modify honor','2','Syntax: .modify honor $field $value\r\n\r\nAdd $value to an honor $field (it\'s just for debug , values won\'t be saved at player logout)\r\nField list: points / rank / todaykills / yesterdaykills / yesterdayhonor /\r\nthisweekkills / thisweekhonor / lastweekkills / lastweekhonor /\r\nlastweekstanding / lifetimedishonorablekills / lifetimehonorablekills ');

INSERT INTO mangos_string (entry,content_default) VALUES (349,"Private ");
INSERT INTO mangos_string (entry,content_default) VALUES (350,"Corporal ");
INSERT INTO mangos_string (entry,content_default) VALUES (351,"Sergeant ");
INSERT INTO mangos_string (entry,content_default) VALUES (352,"Master Sergeant ");
INSERT INTO mangos_string (entry,content_default) VALUES (353,"Sergeant Major ");
INSERT INTO mangos_string (entry,content_default) VALUES (354,"Knight ");
INSERT INTO mangos_string (entry,content_default) VALUES (355,"Knight-Lieutenant ");
INSERT INTO mangos_string (entry,content_default) VALUES (356,"Knight-Captain ");
INSERT INTO mangos_string (entry,content_default) VALUES (357,"Knight-Champion ");
INSERT INTO mangos_string (entry,content_default) VALUES (358,"Lieutenant Commander ");
INSERT INTO mangos_string (entry,content_default) VALUES (359,"Commander ");
INSERT INTO mangos_string (entry,content_default) VALUES (360,"Marshal ");
INSERT INTO mangos_string (entry,content_default) VALUES (361,"Field Marshal ");
INSERT INTO mangos_string (entry,content_default) VALUES (362,"Grand Marshal ");
INSERT INTO mangos_string (entry,content_default) VALUES (363,"Scout ");
INSERT INTO mangos_string (entry,content_default) VALUES (364,"Grunt ");
INSERT INTO mangos_string (entry,content_default) VALUES (365,"Sergeant ");
INSERT INTO mangos_string (entry,content_default) VALUES (366,"Senior Sergeant ");
INSERT INTO mangos_string (entry,content_default) VALUES (367,"First Sergeant ");
INSERT INTO mangos_string (entry,content_default) VALUES (368,"Stone Guard ");
INSERT INTO mangos_string (entry,content_default) VALUES (369,"Blood Guard ");
INSERT INTO mangos_string (entry,content_default) VALUES (370,"Legionnare ");
INSERT INTO mangos_string (entry,content_default) VALUES (371,"Centurion ");
INSERT INTO mangos_string (entry,content_default) VALUES (372,"Champion ");
INSERT INTO mangos_string (entry,content_default) VALUES (373,"Lieutenant General ");
INSERT INTO mangos_string (entry,content_default) VALUES (374,"General ");
INSERT INTO mangos_string (entry,content_default) VALUES (375,"Warlord ");
INSERT INTO mangos_string (entry,content_default) VALUES (376,"High Warlord ");
INSERT INTO mangos_string (entry,content_default) VALUES (377,"Game Master ");
INSERT INTO mangos_string (entry,content_default) VALUES (378,"No Rank ");
INSERT INTO mangos_string (entry,content_default) VALUES (379,"%s (Rank %u)");
INSERT INTO mangos_string (entry,content_default) VALUES (380,"Today: [Honorable Kills: |c0000ff00%u|r] [Dishonorable Kills: |c00ff0000%u|r]");
INSERT INTO mangos_string (entry,content_default) VALUES (381,"Yesterday: [Kills: |c0000ff00%u|r] [Honor: %u]");
INSERT INTO mangos_string (entry,content_default) VALUES (382,"This Week: [Kills: |c0000ff00%u|r] [Honor: %u]");
INSERT INTO mangos_string (entry,content_default) VALUES (383,"Last Week: [Kills: |c0000ff00%u|r] [Honor: %u] [Standing: %u]");
INSERT INTO mangos_string (entry,content_default) VALUES (384,"Life Time: [Honorable Kills: |c0000ff00%u|r] [Dishonorable Kills: |c00ff0000%u|r] [Highest Rank %u: %s]");
