#ifndef __REVISION_SQL_H__
#define __REVISION_SQL_H__
 #define REVISION_DB_REALMD "required_z2768_01_realmd_account_locale_agnostic"
 #define REVISION_DB_CHARACTERS "required_z2770_01_characters_item_instance_duration_default"
 #define REVISION_DB_MANGOS "required_z2771_01_mangos_creature_spawn_data"
#endif // __REVISION_SQL_H__
