#ifndef __REVISION_SQL_H__
#define __REVISION_SQL_H__
 #define REVISION_DB_CHARACTERS "required_z0738_s0041_01_characters_auctionhouse"
 #define REVISION_DB_MANGOS "required_z0764_s0070_01_mangos_reputation_spillover_template"
 #define REVISION_DB_REALMD "required_10008_01_realmd_realmd_db_version"
#endif // __REVISION_SQL_H__
