ALTER TABLE db_version CHANGE COLUMN required_z2487_s2128_12654_01_mangos_creature_template_power required_z2530_sxxxx_xxxxx_01_mangos_gameobject_template bit;

ALTER TABLE `gameobject_template` DROP COLUMN `castBarCaption`;