#!/usr/bin/env bash

while true; do 

    SSHOUTPUT=$(run-on-pi "cat /etc/os-release" | wc -l)

    echo $SSHOUTPUT

    if nc -z localhost 10022 ; then
        echo "Found something on port 10022!"
        exit
    else
        echo "Nothing found on port 10022, sleeping..."
        sleep 10
    fi
done
