DROP TABLE IF EXISTS `string_id`;
CREATE TABLE `string_id`(
`Id` INT(11) UNSIGNED NOT NULL,
`Name` VARCHAR(255) NOT NULL,
PRIMARY KEY(`Id`)
);

ALTER TABLE creature_spawn_data_template ADD COLUMN `StringId` INT(11) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE gameobject_addon ADD COLUMN `StringId` INT(11) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE spawn_group ADD COLUMN `StringId` INT(11) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE creature_template ADD COLUMN `StringId1` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `SpellList`;
ALTER TABLE creature_template ADD COLUMN `StringId2` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `StringId1`;
ALTER TABLE gameobject_template ADD COLUMN `StringId` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `maxgold`;

